DELETE FROM illness;
DELETE FROM person_data;
DELETE FROM address;
DELETE FROM medical_card;
DELETE FROM contact;

ALTER SEQUENCE contact_seq RESTART WITH 1;
ALTER SEQUENCE medical_card_seq RESTART WITH 1;
ALTER SEQUENCE address_seq RESTART WITH 1;
ALTER SEQUENCE person_data_seq RESTART WITH 1;
ALTER SEQUENCE illness_seq RESTART WITH 1;
